routes/web.php
Route::get('/login/{provider}/callback','Auth\SocialController@Callback');
// Route::redirect('/', '/login');
Route::get('/','Landing\LandingController@index');
Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.home')->with('status', session('status'));
    }

    return redirect()->route('admin.home');
});

Route::get('/mytest', function () {
    return view('test');
});

Route::group(['prefix' => 'admin'], function () {
    Auth::routes();
});


Route::get('userVerification/{token}', 'UserVerificationController@approve')->name('userVerification');
Route::get('userVerification/otp/{token}', 'UserVerificationController@approveOTP')->name('userVerification_otp');
Route::post('user/register', 'Auth\RegisterController@store')->name('user_registration');



// Admin
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth', 'subscription_check']], function () {

    //notify
    //Route::get('/test','UserAlertsController@index')->name('notification');
    Route::post('/save-token', 'UserAlertsController@saveToken')->name('save-token');
    Route::post('/send-notification', 'NotificationController@sendNotification_test')->name('send.notification');

    Route::get('/dashboard', 'HomeController@index')->name('home');
    // Route::redirect('/dashboard', '/admin/stores');

    Route::redirect('/dashboard', '/admin/mystore');

    Route::get('/adminDashboard', 'DashboardController@index')->name('dashboard.index');

    Route::get('user-alerts/read', 'UserAlertsController@read');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users

    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');
    // Route::get('/users', 'App\Http\Controllers\UserController@index');

    Route::post('change-user-password/{user_id}', 'UsersController@changePassword')->name('users.changePassword');
    Route::get('accountSettings', 'UsersController@accountSettings')->name('users.accountSettings');
    Route::put('accountSettingsUpdate', 'UsersController@accountSettingsUpdate')->name('users.accountSettingsUpdate');


    // StoreUser
    Route::delete('storeUser/destroy', 'StoreUserController@massDestroy')->name('storeUser.massDestroy');
    Route::resource('storeUser', 'StoreUserController', ['except' => ['edit', 'show']]);
    Route::get('storeUser/{user_id}', 'StoreUserController@show')->name('storeUser.show');
    Route::get('storeUser/{user_id}/edit', 'StoreUserController@edit')->name('storeUser.edit');
    Route::post('storeUser/{user_id}/edit', 'StoreUserController@edit')->name('storeUser.edit');
    Route::post('change-password/{user_id}', 'StoreUserController@changePassword')->name('storeUser.changePassword');
    // Route::get('accountSettings', 'StoreUserController@accountSettings')->name('storeUser.accountSettings');
    Route::put('accountSettingsUpdate', 'StoreUserController@accountSettingsUpdate')->name('storeUser.accountSettingsUpdate');

    //Devices
    Route::resource('devices', 'DevicesController');
    Route::resource('userTranscations', 'UserTransactionsController');

    // Audit Logs
    Route::resource('audit-logs', 'AuditLogsController', ['except' => ['create', 'store', 'edit', 'update', 'destroy']]);

    // Product Categories
    Route::delete('product-categories/destroy', 'ProductCategoryController@massDestroy')->name('product-categories.massDestroy');
    Route::post('product-categories/media', 'ProductCategoryController@storeMedia')->name('product-categories.storeMedia');
    Route::post('product-categories/ckmedia', 'ProductCategoryController@storeCKEditorImages')->name('product-categories.storeCKEditorImages');
    Route::resource('product-categories', 'ProductCategoryController');

    Route::post('ajaxaddcategory', 'ProductCategoryController@ajaxAddCategory')->name('product-categories.ajaxAddCategory');

    // Product Tags
    Route::delete('product-tags/destroy', 'ProductTagController@massDestroy')->name('product-tags.massDestroy');
    Route::resource('product-tags', 'ProductTagController');

    // Product Attribute
    Route::get('product-attributes/add/{id}', 'ProductAttributeController@add')->name('productAttributes.add');
    Route::delete('product-attributes/delete/{id}', 'ProductAttributeController@AttributeDestroy')->name('productAttributes.attributedestroy');
    Route::resource('product-attributes', 'ProductAttributeController');

    //Subscriptions - Packages and Plans
    Route::get('packages/add/{id}/{plan_id}', 'PackageController@addFeature')->name('packages.addfeature');
    Route::get('packages/add/{id}/', 'PackageController@addPlanFeature')->name('packages.addPlanFeature');
    Route::delete('packages/remove_feature/{id}', 'PackageController@removeFeature')->name('packages.removeFeature');
    Route::get('packages/add_on/{id}/{user_id}', 'PackageAddOnController@addFeatureAddOn')->name('package_add_ons.addfeatureaddon');
    Route::delete('packages/remove_add_on/{id}', 'PackageAddOnController@removeAddOnFeature')->name('package_add_ons.removeAddOnFeature');

    Route::resource('packages', 'PackageController');
    Route::resource('package_add_ons', 'PackageAddOnController');
    Route::resource('plan_subscription_features', 'PlanSubscriptionFeaturesController');



    //User Payments
    Route::resource('user_payments', 'UserPaymentsController');

    //Pos
    Route::get('pos/ajaxProductData', 'PosController@ajaxProductsData')->name('pos.ajaxProductsData');
    Route::post('pos/placeOrder', 'PosController@placeOrder')->name('pos.order');
    Route::post('pos/update', 'PosController@update')->name('pos.update');
    Route::resource('pos', 'PosController',['except' => [ 'update' ]]);

    //shipping

    // Products
    Route::delete('products/destroy', 'ProductController@massDestroy')->name('products.massDestroy');
    Route::post('products/media', 'ProductController@storeMedia')->name('products.storeMedia');
    Route::post('products/log', 'ProductController@imagelog')->name('products.log');
    Route::post('products/sku', 'ProductController@productsku')->name('products.sku');
    Route::post('products/logshow', 'ProductController@imagelogshow')->name('products.logshow');
    Route::post('products/ckmedia', 'ProductController@storeCKEditorImages')->name('products.storeCKEditorImages');
    Route::resource('products', 'ProductController');
    Route::post('products/parse-csv-import', 'ProductController@parseCsvImports')->name('products.parseCsvImport');
    Route::post('products/process-csv-import', 'ProductController@processCsvImports')->name('products.processCsvImport');

    Route::get('ajaxData', 'ProductController@ajaxData')->name('products.ajaxData');
    Route::get('ajaxSelectProducts', 'ProductController@ajaxSelectProducts')->name('products.ajaxSelectProducts');
    Route::get('AddedajaxData', 'ProductController@AddedajaxData')->name('products.AddedajaxData');
    Route::get('myproducts', 'ProductController@product_list')->name('products.product_list');

    Route::post('products/updates', 'ProductController@updateProduct')->name('product_list.update');
    Route::post('products/removeimg', 'ProductController@removeImg')->name('products.removeimg');

    // Faq Categories
    Route::delete('faq-categories/destroy', 'FaqCategoryController@massDestroy')->name('faq-categories.massDestroy');
    Route::resource('faq-categories', 'FaqCategoryController');

    // Faq Questions
    Route::delete('faq-questions/destroy', 'FaqQuestionController@massDestroy')->name('faq-questions.massDestroy');
    Route::resource('faq-questions', 'FaqQuestionController');

    // Content Categories
    Route::delete('content-categories/destroy', 'ContentCategoryController@massDestroy')->name('content-categories.massDestroy');
    Route::resource('content-categories', 'ContentCategoryController');

    // Content Tags
    Route::delete('content-tags/destroy', 'ContentTagController@massDestroy')->name('content-tags.massDestroy');
    Route::resource('content-tags', 'ContentTagController');

    // Content Pages
    Route::delete('content-pages/destroy', 'ContentPageController@massDestroy')->name('content-pages.massDestroy');
    Route::post('content-pages/media', 'ContentPageController@storeMedia')->name('content-pages.storeMedia');
    Route::post('content-pages/ckmedia', 'ContentPageController@storeCKEditorImages')->name('content-pages.storeCKEditorImages');
    Route::resource('content-pages', 'ContentPageController');

    // User Alerts
    Route::delete('user-alerts/destroy', 'UserAlertsController@massDestroy')->name('user-alerts.massDestroy');
    Route::resource('user-alerts', 'UserAlertsController', ['except' => ['edit', 'update']]);

    // Teams
    Route::delete('teams/destroy', 'TeamController@massDestroy')->name('teams.massDestroy');
    Route::resource('teams', 'TeamController');

    // Arobjects
    Route::delete('arobjects/destroy', 'ArobjectController@massDestroy')->name('arobjects.massDestroy');
    Route::post('arobjects/media', 'ArobjectController@storeMedia')->name('arobjects.storeMedia');
    Route::post('arobjects/ckmedia', 'ArobjectController@storeCKEditorImages')->name('arobjects.storeCKEditorImages');
    Route::resource('arobjects', 'ArobjectController');

    Route::post('arobjects/objupload', 'ArobjectController@createorupdate')->name('arobjects.objupload');
    Route::post('arobjects/updates', 'ArobjectController@updateObject')->name('arobjects.updateObject');


    // Videos
    Route::delete('videos/destroy', 'VideosController@massDestroy')->name('videos.massDestroy');

app/Models/Device.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Device extends Model
{
    use HasFactory;
    public $table = 'devices';

    const STATUS_SELECT = [
        '1' => 'Active',
        '0' => 'Deactive',
        '2' => 'Blocked',
    ];

    protected $dates = [
        'created_at',
        'updated_at',
        'start_date',
        'end_date',
    ];

    protected $fillable = [
        'key',
        'device_name',
        'device_id',
        'start_date',
        'end_date',
        'status',
        'meta_data', 
        'user_id',
    ];

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function getStartDateAttribute($date)
    {
        return Carbon::createFromFormat('Y-m-d H:i:s', $date)->format('Y-m-d\TH:i');
    }

    public function getEndDateAttribute($date)
    {
        return Carbon::createFromFormat('Y-m-d H:i:s', $date)->format('Y-m-d\TH:i');
    }
}

app/Models/Statistics/Device.php
<?php

declare(strict_types=1);

namespace  App\Models\Statistics;

use Illuminate\Database\Eloquent\Model;
use Rinvex\Support\Traits\ValidatingTrait;
use Illuminate\Database\Eloquent\Relations\HasMany;



class Device extends Model
{
    use ValidatingTrait;

    /**
     * {@inheritdoc}
     */
    protected $fillable = [
        'family',
        'model',
        'brand',
        'team_id',
    ];

    /**
     * {@inheritdoc}
     */
    protected $casts = [
        'family' => 'string',
        'model' => 'string',
        'brand' => 'string',
    ];

    /**
     * {@inheritdoc}
     */
    public $timestamps = false;

    /**
     * {@inheritdoc}
     */
    protected $observables = [
        'validating',
        'validated',
    ];

    /**
     * The default rules that the model will validate against.
     *
     * @var array
     */
    protected $rules = [
        'family' => 'required|string',
        'model' => 'nullable|string',
        'brand' => 'nullable|string',
    ];

    /**
     * Whether the model should throw a
     * ValidationException if it fails validation.
     *
     * @var bool
     */
    protected $throwValidationExceptions = true;

    /**
     * Create a new Eloquent model instance.
     *
     * @param array $attributes
     */
    public function __construct(array $attributes = [])
    {
        parent::__construct($attributes);

        $this->setTable(config('rinvex.statistics.tables.devices'));
    }

    /**
     * The device may have many requests.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function requests(): HasMany
    {
        return $this->hasMany(config('rinvex.statistics.models.request'), 'device_id', 'id');
    }

    public function team()
    {
        return $this->belongsTo(Team::class, 'team_id');
    }
}

app/Http/Controllers/Admin/DevicesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Device;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\User;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;
use Webpatser\Uuid\Uuid;
use Carbon\Carbon;
use Illuminate\Support\Facades\Validator;

class DevicesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $device = Device::all();

        return view('admin.devices.index', compact('device'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        generate:
        $keyDigit = 4;
        $key = strtoupper(str::random($keyDigit));
        $keys = str_split($key, strlen($key)/($keyDigit/4));
        $uuid_key = "";
        foreach($keys as $k) {
            if($uuid_key == "")
                $uuid_key = $k;
            else
                $uuid_key .= "-".$k;
        }

        $validator = Validator::make(["key" => $uuid_key], [
            'key' => 'required|unique:devices',
        ]);
  
        if ($validator->fails()) {
            goto generate;
        }

        // dd($uuid_key);
        Device::create([
            'key' =>$uuid_key,
            'user_id' => auth()->user()->id,
            'status' => 0]);
            return redirect()->back();
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        return redirect()->route('admin.devices.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\device  $device
     * @return \Illuminate\Http\Response
     */
    public function show(device $device)
    {
        //

        return view('admin.devices.show',compact('device'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\device  $device
     * @return \Illuminate\Http\Response
     */
    public function edit(device $device)
    {
        //
        $users = User::all()->pluck('name', 'id')->prepend(trans('global.pleaseSelect'), '');
        return view('admin.devices.edit', compact('device','users'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\device  $device
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, device $device)
    {
        //
        $device->update($request->all());
        return redirect()->back()->with('message','Update Device successfully.');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\device  $device
     * @return \Illuminate\Http\Response
     */
    public function destroy(device $device)
    {
        //
        $device->delete();

        return back();
    }
}

resources/views/admin/devices/edit.blade.php
@extends('layouts.admin')
@section('content') 
<div class="card">
    <div class="card-header">
        Edit Device
    </div>
    <div class="card-body">
        <form method="POST" action="{{ route("admin.devices.update", [$device->id]) }}" enctype="multipart/form-data">
            @method('PUT')
            @csrf
            <div class="form-group">
                <label for="key"> Key</label>
                    <input type="text" class="form-control"  name="key" id="key" value="{{ old('key', $device->key) }}" disabled>
            </div>
            <div class="form-group">
                <label for="device_name"> Device Name</label>
                    <input type="text" class="form-control"  name="device_name" id="device_name" value="{{ old('device_name', $device->device_name) }}" disabled>
            </div>
            <div class="form-group">
                <label for="device_id"> Device Id</label>
                    <input type="text" class="form-control"  name="device_id" id="device_id" value="{{ old('device_id', $device->device_id) }}" disabled>
            </div>
            <div class="form-group">
                <label for="start_date"> Device Start Date</label>
                    <input type="datetime-local" class="form-control"  name="start_date" id="start_date" value="{{ old('start_date', $device->start_date) }}" >
            </div>
            <div class="form-group">
                <label for="end_date"> Device End Date</label>
                    <input type="datetime-local" class="form-control"  name="end_date" id="end_date" value="{{ old('end_date', $device->end_date) }}" >
            </div>
            <div class="form-group">
                <label>Status</label>
                <select class="form-control" name="status">
                    @foreach(App\Models\Device::STATUS_SELECT as $key => $label)
                    <option value="{{ $key }}" {{ old('status', $device->status) == $key ? 'selected' : '' }}>{{ $label }}</option>
                    @endforeach
                </select>
            </div>
            <div class="form-group">
                <label for="meta_data"> Meta Data</label>
                    <input type="text" class="form-control"  name="meta_data" id="meta_data" value="{{ old('status', $device->meta_data) }}" disabled>
            </div>
            <div class="form-group">
                <label for="user_id">User</label>
                <select class="form-control select2 {{ $errors->has('team') ? 'is-invalid' : '' }}" name="user_id" id="user_id">
                    @foreach($users as $id => $user)
                        <option value="{{ $id }}" {{ old('user_id', $device->user_id) == $id ? 'selected' : '' }}>{{ $user }}</option>
                    @endforeach
                </select>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/admin/devices/index.blade.php
@extends('layouts.admin')
@section('content')
<div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route("admin.devices.create") }}">
                Create Device
            </a>
        </div>
    </div>
<div class="card">
    <div class="card-header">
        User List
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable datatable-User">
                <thead>
                    <tr>
                        <th>
                            ID
                        </th>
                        <th>
                            Key
                        </th>
                        <th>
                            Device Name
                        </th>
                        <th>
                            Device Id
                        </th>
                        <!-- <th>
                            {{ trans('cruds.user.fields.email_verified_at') }}
                        </th>
                        <th>
                            {{ trans('cruds.user.fields.approved') }}
                        </th>
                        <th>
                            {{ trans('cruds.user.fields.verified') }}
                        </th>
                        <th>
                            {{ trans('cruds.user.fields.roles') }}
                        </th> -->
                        <th>
                            Device start date
                        </th>
                        <th>
                            Device end date
                        </th>
                        <th>
                             status
                        </th>
                        <th>
                             Meta Data
                        </th>
                        <th>
                            User Id
                        </th>
                        <th>
                            &nbsp;Actions
                        </th>
                    </tr>
                </thead>
                <tbody>
                @foreach($device as $key => $device)
                        
                        <tr data-entry-id="{{ $device->id }}">
                            <td>
                                {{ $device->id ?? '' }}
                            </td>
                            <td>
                                {{ $device->key ?? '' }}
                            </td>
                            <td>
                                {{ $device->device_name ?? '' }}
                            </td>
                            <td>
                                {{ $device->device_id ?? '' }}
                            </td>
                            <td>
                                {{ $device->start_date ?? '' }}
                            </td>
                            
                            <td>
                                {{ $device->end_date ?? '' }}
                            </td>
                            
                            <td>
                                {{ $device->status ?? '' }}
                            </td>
                            <td>
                                {{ $device->meta_data}}
                            </td>    
                            <td>
                                {{ $device->user_id}}
                            </td>  
                            
                            <td>
                                    <a class="btn btn-xs btn-primary btn-icon" href="{{ route('admin.devices.show',$device->id) }}">
                                        <i class="feather icon-eye"></i>
                                    </a>

                                    <a class="btn btn-xs btn-info btn-icon" href="{{ route('admin.devices.edit', $device->id) }}">
                                        <i class="feather icon-edit"></i>
                                    </a>

                                    <form action="{{ route('admin.devices.destroy', $device->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <button type="submit" class="btn btn-xs btn-danger btn-icon"><i class="feather icon-trash"></i></button>
                                    </form>
                        
                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>   

@endsection

resources/views/admin/devices/show.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        Show Devices
    </div>
    <div class="card-body">
        <div class="form-group">
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.devices.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <th>
                            {{ trans('cruds.user.fields.id') }}
                        </th>
                        <td>
                            {{ $device->id }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            Key
                        </th>
                        <td>
                        {{ $device->key }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            Device Name
                        </th>
                        <td>
                        {{ $device->device_name }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                        Device Id
                        </th>
                        <td>
                        {{ $device->device_id }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                        Device start date
                        </th>
                        <td>
                        {{ $device->start_date }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                        Device end date
                        </th>
                        <td>
                        {{ $device->end_date }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                        status
                        </th>
                        <td>
                        {{ $device->status }} 
                        </td>
                    </tr>
                    <tr>
                        <th>
                        Meta Data
                        </th>
                        <td>
                        {{ $device->meta_data }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                        User Id
                        </th>
                        <td>
                        {{ $device->user_id }}
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.devices.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
        </div>
    </div>
</div>
@endsection