routes/web.php
    Route::POST('enquiry/status', 'EnquiryController@updateEnquiryStatus')->name('enquiry.updateStatus');
    Route::get('enquiry', 'EnquiryController@index')->name('enquiry.index');
    Route::get('enquiry/ajaxData', 'EnquiryController@enquiryAjaxData')->name('enquiry.ajaxData');
    Route::get('enquiry/list/{id}', 'EnquiryController@show')->name('enquiry.show');


    //coupons
    Route::get('coupons','CouponController@index')->name('coupons.index');

    //Referral
    Route::get('referrals','ReferralController@index')->name('referrals.index');

    //Variants
    Route::get('variants','VariantsController@index')->name('variants.index');

    //Product Variants
    Route::get('product-variants/{product_id}','ProductVariantsController@index')->name('productVariants.index');
    Route::get('product-variants/show/{product_id}','ProductVariantsController@show')->name('productVariants.show');
    Route::get('product-variants/edit/{product_id}','ProductVariantsController@edit')->name('productVariants.edit');
    Route::put('product-variants/update/{product_id}','ProductVariantsController@update')->name('productVariants.update');
    Route::get('product-variants/delete/{product_id}','ProductVariantsController@delete')->name('productVariants.destroy');
    Route::get('product-variants/add_variant/{variant_id}','ProductVariantsController@addVariant')->name('productVariants.addVariant');
    Route::post('product-variants/media', 'ProductVariantsController@storeMedia')->name('productVariants.storeMedia');
    Route::post('product-variants/ckmedia', 'ProductVariantsController@storeCKEditorImages')->name('productVariants.storeCKEditorImages');
    Route::post('product-variants/varremoveimg', 'ProductVariantsController@removeImg')->name('productVariants.varremoveimg');


    //Statistics
    Route::get('stats_index', 'Analytics\StatisticsController@index')->name('stats.index');
    Route::get('stats/columns', 'Analytics\StatisticsController@GetTableName')->name('stats.getTableName');
    Route::get('stats/data', 'Analytics\StatisticsController@StatsData')->name('stats.getStatsData');
    Route::get('stats/chart', 'Analytics\StatisticsController@statsChart')->name('stats.getStatChart');
    Route::get('stats/icustomers', 'Analytics\StatisticsController@customerStat')->name('stats.getCustomerstat');
    Route::get('stats/{sales?}', 'Analytics\StatisticsController@salesStat')->name('stats.getSalesstat');


    // Assets
    Route::delete('assets/destroy', 'AssetsController@massDestroy')->name('assets.massDestroy');
    Route::post('assets/media', 'AssetsController@storeMedia')->name('assets.storeMedia');
    Route::post('assets/ckmedia', 'AssetsController@storeCKEditorImages')->name('assets.storeCKEditorImages');
    Route::resource('assets', 'AssetsController');

    // Currencies
    Route::delete('currencies/destroy', 'CurrencyController@massDestroy')->name('currencies.massDestroy');
    Route::resource('currencies', 'CurrencyController');

    // Company Infos
    Route::delete('company-infos/destroy', 'CompanyInfoController@massDestroy')->name('company-infos.massDestroy');
    Route::resource('company-infos', 'CompanyInfoController');

    // Countries
    Route::delete('countries/destroy', 'CountriesController@massDestroy')->name('countries.massDestroy');
    Route::resource('countries', 'CountriesController');

    // States
    Route::delete('states/destroy', 'StateController@massDestroy')->name('states.massDestroy');
    Route::resource('states', 'StateController');

    // Cities
    Route::delete('cities/destroy', 'CityController@massDestroy')->name('cities.massDestroy');
    Route::resource('cities', 'CityController');

    // User Infos
    Route::delete('user-infos/destroy', 'UserInfoController@massDestroy')->name('user-infos.massDestroy');
    Route::resource('user-infos', 'UserInfoController');


    //mobileLogin
    Route::get('account/mobileLogin','MobileLoginController@index')->name('mobileLogin');

    // User Settings
    Route::get('userSettings/createExtraCharge/{extra_charge_id}', 'UserSettingsController@createExtraCharge')->name('userSettings.createExtraCharge');
    Route::get('userSettings', 'UserSettingsController@index')->name('userSettings.index');
    Route::post('userUpdate', 'UserSettingsController@update')->name('userSettings.update');
    Route::post('saveToken','UserSettingsController@saveToken')->name('notification.save');

    Route::post('userSettings/media', 'UserSettingsController@storeMedia')->name('userSettings.storeMedia');

    Route::group(['middleware' => 'shared'], function () {
        Route::get('catalog/pdf/{shareable_link}', 'PdfController@export_catalog_pdf')->name('export_catalog_pdf');
    });

    Route::get('pos/print_invoice/{orders}', 'PdfController@print_pos_invoice_pdf')->name('print_pos_invoice_pdf');
    Route::get('orders/pdf/{orders}', 'PdfController@export_order_pdf')->name('export_order_pdf');
    Route::get('labels/pdf/{orders}', 'PdfController@export_label_pdf')->name('export_label_pdf');
    Route::get('invoice/pdf/{orders}', 'PdfController@export_invoice_pdf')->name('export_invoice_pdf');
    Route::get('orders/print/{payment_id}', 'PdfController@print_user_payment_pdf')->name('print_user_payment_pdf');
    Route::get('user_payments/pdf/{payment_id}', 'PdfController@export_user_payment_pdf')->name('export_user_payment_pdf');



    Route::get('messenger', 'MessengerController@index')->name('messenger.index');
    Route::get('messenger/create', 'MessengerController@createTopic')->name('messenger.createTopic');
    Route::post('messenger', 'MessengerController@storeTopic')->name('messenger.storeTopic');
    Route::get('messenger/inbox', 'MessengerController@showInbox')->name('messenger.showInbox');
    Route::get('messenger/outbox', 'MessengerController@showOutbox')->name('messenger.showOutbox');
    Route::get('messenger/{topic}', 'MessengerController@showMessages')->name('messenger.showMessages');
    Route::delete('messenger/{topic}', 'MessengerController@destroyTopic')->name('messenger.destroyTopic');
    Route::post('messenger/{topic}/reply', 'MessengerController@replyToTopic')->name('messenger.reply');
    Route::get('messenger/{topic}/reply', 'MessengerController@showReply')->name('messenger.showReply');


    //maintanance mode
    Route::get('maintenance', 'MaintenanceController@index')->name('maintenance');

    Route::get('/clearcache', function () {
        Artisan::call('cache:clear');
        Artisan::call('route:clear');
        Artisan::call('config:clear');
        Artisan::call('view:clear');
        return "Cache is cleared";
    });

});



Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/subscription/getpaymentdetails', 'SubscriptionController@getPaymentDetails')->name('subscription.getPaymentDetails');
    Route::get('/subscription/myPlan', 'SubscriptionController@myPlan')->name('subscription.myPlan');
    Route::get('/subscription/new_user_show/{plan_id}', 'SubscriptionController@newUserShow')->name('subscription.newUserShow');
    Route::get('/subscription/show/{subscription}/{id}', 'SubscriptionController@show')->name('subscription.show');
    Route::post('/subscription', 'SubscriptionController@create')->name('subscription.create');
    Route::post('/subscription/upgrade', 'SubscriptionController@upgradePlan')->name('subscription.upgradePlan');
    Route::post('/subscription/downgrade', 'SubscriptionController@downgradePlan')->name('subscription.downgradePlan');
    Route::get('/subscription/renewSubscription', 'SubscriptionController@renewSubscription')->name('subscription.renewSubscription');
    Route::resource('subscriptions', 'SubscriptionController');
    Route::post('/adminSubscription/createSubscription', 'AdminSubscriptionController@createSubscription')->name('adminSubscription.createSubscription');
    Route::post('/adminSubscription/upgradeSubscription', 'AdminSubscriptionController@upgradeSubscription')->name('adminSubscription.upgradeSubscription');
    Route::post('/adminSubscription/downgradeSubscription', 'AdminSubscriptionController@downgradeSubscription')->name('adminSubscription.downgradeSubscription');
    Route::post('/adminSubscription/renewSubscription', 'AdminSubscriptionController@renewSubscription')->name('adminSubscription.renewSubscription');
    Route::get('/adminSubscription/userSubscription/{user_id}', 'AdminSubscriptionController@userSubscription')->name('adminSubscription.userSubscription');
    Route::post('/adminSubscription/assignSubscription', 'AdminSubscriptionController@assignSubscription')->name('adminSubscription.Subscription');
    Route::post('/adminSubscription/updateSubscription', 'AdminSubscriptionController@updateSubscription')->name('adminSubscription.updateSubscription');
    Route::get('/impersonate/{id}', 'UsersController@impersonate')->name('users.impersonate');
    Route::get('/stopimpersonate', 'UsersController@stopImpersonate')->name('users.stopimpersonate');
    Route::post('/adminSubscription/planData','AdminSubscriptionController@planData')->name('plan.data');
    Route::post('/adminSubscription/planDetails','AdminSubscriptionController@planDetails')->name('plan.details');
    Route::post('/adminSubscription/subscriptionPayment','AdminSubscriptionController@paymentDetails')->name('subscriptionPayment.data');

    Route::get('mystore', 'CampaignsController@storeIndex')->name('campaigns.storeIndex');
    Route::post('setDomain', 'UserSettingsController@set_domain')->name('userSettings.set_domain');
});

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin'], function () {
    Route::get('mobileview/razorpay', 'PaymentController@razorpay_mobile')->name('payment.razorpay_mobile');
});

// in a routes file


// https://stackoverflow.com/questions/26783770/laravel-route-group-match-whole-domain

app/State.php
<?php

namespace App;

use App\Traits\Auditable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class State extends Model
{
    use SoftDeletes, Auditable;

    public $table = 'states';

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'code',
        'name',
        'created_at',
        'updated_at',
        'deleted_at',
    ];
}

app/Http/Controllers/Admin/StateController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\MassDestroyStateRequest;
use App\Http\Requests\StoreStateRequest;
use App\Http\Requests\UpdateStateRequest;
use App\State;
use Gate;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;
use Yajra\DataTables\Facades\DataTables;

class StateController extends Controller
{
    public function index(Request $request)
    {
        abort_if(Gate::denies('state_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        if ($request->ajax()) {
            $query = State::query()->select(sprintf('%s.*', (new State)->table));
            $table = Datatables::of($query);

            $table->addColumn('placeholder', '&nbsp;');
            $table->addColumn('actions', '&nbsp;');

            $table->editColumn('actions', function ($row) {
                $viewGate      = 'state_show';
                $editGate      = 'state_edit';
                $deleteGate    = 'state_delete';
                $crudRoutePart = 'states';

                return view('partials.datatablesActions', compact(
                    'viewGate',
                    'editGate',
                    'deleteGate',
                    'crudRoutePart',
                    'row'
                ));
            });

            $table->editColumn('id', function ($row) {
                return $row->id ? $row->id : "";
            });
            $table->editColumn('code', function ($row) {
                return $row->code ? $row->code : "";
            });
            $table->editColumn('name', function ($row) {
                return $row->name ? $row->name : "";
            });

            $table->rawColumns(['actions', 'placeholder']);

            return $table->make(true);
        }

        return view('admin.states.index');
    }

    public function create()
    {
        abort_if(Gate::denies('state_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.states.create');
    }

    public function store(StoreStateRequest $request)
    {
        $state = State::create($request->all());

        return redirect()->route('admin.states.index');
    }

    public function edit(State $state)
    {
        abort_if(Gate::denies('state_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.states.edit', compact('state'));
    }

    public function update(UpdateStateRequest $request, State $state)
    {
        $state->update($request->all());

        return redirect()->route('admin.states.index');
    }

    public function show(State $state)
    {
        abort_if(Gate::denies('state_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.states.show', compact('state'));
    }

    public function destroy(State $state)
    {
        abort_if(Gate::denies('state_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $state->delete();

        return back();
    }

    public function massDestroy(MassDestroyStateRequest $request)
    {
        State::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }
}

resources/views/admin/states/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('cruds.state.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.states.store") }}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label class="required" for="code">{{ trans('cruds.state.fields.code') }}</label>
                <input class="form-control {{ $errors->has('code') ? 'is-invalid' : '' }}" type="text" name="code" id="code" value="{{ old('code', '') }}" required>
                @if($errors->has('code'))
                    <div class="invalid-feedback">
                        {{ $errors->first('code') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.state.fields.code_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="name">{{ trans('cruds.state.fields.name') }}</label>
                <input class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" type="text" name="name" id="name" value="{{ old('name', '') }}" required>
                @if($errors->has('name'))
                    <div class="invalid-feedback">
                        {{ $errors->first('name') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.state.fields.name_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/states/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} {{ trans('cruds.state.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.states.update", [$state->id]) }}" enctype="multipart/form-data">
            @method('PUT')
            @csrf
            <div class="form-group">
                <label class="required" for="code">{{ trans('cruds.state.fields.code') }}</label>
                <input class="form-control {{ $errors->has('code') ? 'is-invalid' : '' }}" type="text" name="code" id="code" value="{{ old('code', $state->code) }}" required>
                @if($errors->has('code'))
                    <div class="invalid-feedback">
                        {{ $errors->first('code') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.state.fields.code_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="name">{{ trans('cruds.state.fields.name') }}</label>
                <input class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" type="text" name="name" id="name" value="{{ old('name', $state->name) }}" required>
                @if($errors->has('name'))
                    <div class="invalid-feedback">
                        {{ $errors->first('name') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.state.fields.name_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/states/index.blade.php
@extends('layouts.admin')
@section('content')
@can('state_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route("admin.states.create") }}">
                {{ trans('global.add') }} {{ trans('cruds.state.title_singular') }}
            </a>
        </div>
    </div>
@endcan
<div class="card">
    <div class="card-header">
        {{ trans('cruds.state.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <table class=" table table-bordered table-striped table-hover ajaxTable datatable datatable-State">
            <thead>
                <tr>
                    <th width="10">

                    </th>
                    <th>
                        {{ trans('cruds.state.fields.id') }}
                    </th>
                    <th>
                        {{ trans('cruds.state.fields.code') }}
                    </th>
                    <th>
                        {{ trans('cruds.state.fields.name') }}
                    </th>
                    <th>
                        &nbsp;
                    </th>
                </tr>
            </thead>
        </table>
    </div>
</div>



@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('state_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}';
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.states.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).data(), function (entry) {
          return entry.id
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  let dtOverrideGlobals = {
    buttons: dtButtons,
    processing: true,
    serverSide: true,
    retrieve: true,
    aaSorting: [],
    ajax: "{{ route('admin.states.index') }}",
    columns: [
      { data: 'placeholder', name: 'placeholder' },
{ data: 'id', name: 'id' },
{ data: 'code', name: 'code' },
{ data: 'name', name: 'name' },
{ data: 'actions', name: '{{ trans('global.actions') }}' }
    ],
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  };
  $('.datatable-State').DataTable(dtOverrideGlobals);
    $('a[data-toggle="tab"]').on('shown.bs.tab', function(e){
        $($.fn.dataTable.tables(true)).DataTable()
            .columns.adjust();
    });
});

</script>
@endsection

resources/views/admin/states/show.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.show') }} {{ trans('cruds.state.title') }}
    </div>

    <div class="card-body">
        <div class="form-group">
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.states.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <th>
                            {{ trans('cruds.state.fields.id') }}
                        </th>
                        <td>
                            {{ $state->id }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.state.fields.code') }}
                        </th>
                        <td>
                            {{ $state->code }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.state.fields.name') }}
                        </th>
                        <td>
                            {{ $state->name }}
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.states.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
        </div>
    </div>
</div>



@endsection